<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Challenge-2" data-toc-modified-id="Challenge-2-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Challenge 2</a></span><ul class="toc-item"><li><span><a href="#Problem-Solving-Iteration-1" data-toc-modified-id="Problem-Solving-Iteration-1-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Problem Solving Iteration 1</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#The-Total-field-is-computed-based-on-HP,-Attack,-Defense,-Sp.-Atk,-Sp.-Def,-and-Speed." data-toc-modified-id="The-Total-field-is-computed-based-on-HP,-Attack,-Defense,-Sp.-Atk,-Sp.-Def,-and-Speed.-1.1.0.1"><span class="toc-item-num">1.1.0.1&nbsp;&nbsp;</span>The <code>Total</code> field is computed based on <code>HP</code>, <code>Attack</code>, <code>Defense</code>, <code>Sp. Atk</code>, <code>Sp. Def</code>, and <code>Speed</code>.</a></span></li></ul></li></ul></li><li><span><a href="#Problem-Solving-Iteration-2" data-toc-modified-id="Problem-Solving-Iteration-2-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Problem Solving Iteration 2</a></span><ul class="toc-item"><li><span><a href="#Which-pokemon-type-is-most-likely-to-have-the-highest-Total-value?" data-toc-modified-id="Which-pokemon-type-is-most-likely-to-have-the-highest-Total-value?-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Which pokemon type is most likely to have the highest <code>Total</code> value?</a></span><ul class="toc-item"><li><span><a href="#Type-1-and-Type-2-string-variables-need-to-be-converted-to-numerical-variables-in-order-to-identify-the-relationship-between-Total-and-the-pokemon-type." data-toc-modified-id="Type-1-and-Type-2-string-variables-need-to-be-converted-to-numerical-variables-in-order-to-identify-the-relationship-between-Total-and-the-pokemon-type.-1.2.1.1"><span class="toc-item-num">1.2.1.1&nbsp;&nbsp;</span><code>Type 1</code> and <code>Type 2</code> string variables need to be converted to numerical variables in order to identify the relationship between <code>Total</code> and the pokemon type.</a></span></li><li><span><a href="#How-to-convert-two-string-variables-to-numerical?" data-toc-modified-id="How-to-convert-two-string-variables-to-numerical?-1.2.1.2"><span class="toc-item-num">1.2.1.2&nbsp;&nbsp;</span>How to convert two string variables to numerical?</a></span></li><li><span><a href="#In-the-next-cell,-use-One-Hot-Encoding-to-encode-Type-1-and-Type-2.-Use-the-pokemon-type-values-as-the-names-of-the-numerical-fields-you-create." data-toc-modified-id="In-the-next-cell,-use-One-Hot-Encoding-to-encode-Type-1-and-Type-2.-Use-the-pokemon-type-values-as-the-names-of-the-numerical-fields-you-create.-1.2.1.3"><span class="toc-item-num">1.2.1.3&nbsp;&nbsp;</span>In the next cell, use One Hot Encoding to encode <code>Type 1</code> and <code>Type 2</code>. Use the pokemon type values as the names of the numerical fields you create.</a></span></li></ul></li></ul></li><li><span><a href="#Problem-Solving-Iteration-3" data-toc-modified-id="Problem-Solving-Iteration-3-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Problem Solving Iteration 3</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#There-are-relationships-between-Total-and-the-encoded-pokemon-type-variables-and-we-need-to-identify-the-correlations." data-toc-modified-id="There-are-relationships-between-Total-and-the-encoded-pokemon-type-variables-and-we-need-to-identify-the-correlations.-1.3.0.1"><span class="toc-item-num">1.3.0.1&nbsp;&nbsp;</span>There are relationships between <code>Total</code> and the encoded pokemon type variables and we need to identify the correlations.</a></span></li><li><span><a href="#How-to-identify-the-relationship-between-Total-and-the-encoded-pokemon-type-fields?" data-toc-modified-id="How-to-identify-the-relationship-between-Total-and-the-encoded-pokemon-type-fields?-1.3.0.2"><span class="toc-item-num">1.3.0.2&nbsp;&nbsp;</span>How to identify the relationship between <code>Total</code> and the encoded pokemon type fields?</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Bonus-Question" data-toc-modified-id="Bonus-Question-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Bonus Question</a></span></li></ul></div>

# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [5]:
# Importing the dataset from Ironhack's database
df=pd.read_csv(r'D:/Téléchargements/pokemon.csv')
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [11]:
# your code here
#Total is the sum of other columns
df['Total1']=df[['HP','Attack','Defense','Sp. Atk','Sp. Def','Speed']].sum(axis=1)
df
df['Total1'].sum()==df['Total'].sum()

True

Comment: Yeah, Total is just a sum of all those columns

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [16]:
# your code here
from sklearn.preprocessing import LabelBinarizer # hot encoding method 2
y= LabelBinarizer().fit_transform(df['Type 1'])
print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
y=pd.get_dummies(df['Type 1'])

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0      0     0       0         0      0         0     0       0      0      1   
1      0     0       0         0      0         0     0       0      0      1   
2      0     0       0         0      0         0     0       0      0      1   
3      0     0       0         0      0         0     0       0      0      1   
4      0     0       0         0      0         0     1       0      0      0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795    0     0       0         0      0         0     0       0      0      0   
796    0     0       0         0      0         0     0       0      0      0   
797    0     0       0         0      0         0     0       0      0      0   
798    0     0       0         0      0         0     0       0      0      0   
799    0     0       0         0      0         0     1       0      0      0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0         0    0       0       0        0     0      0      0  
1         0    0       0       0        0     0      0      0  
2         0    0       0       0        0     0      0      0  
3         0    0       0       0        0     0      0      0  
4         0    0       0       0        0     0      0      0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795       0    0       0       0        0     1      0      0  
796       0    0       0       0        0     1      0      0  
797       0    0       0       0        1     0      0      0  
798       0    0       0       0        1     0      0      0  
799       0    0       0       0        0     0      0      0  

[800 rows x 18 columns]

In [28]:
x=pd.get_dummies(df['Type 2'])
x

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0      0     0       0         0      0         0     0       0      0      0   
1      0     0       0         0      0         0     0       0      0      0   
2      0     0       0         0      0         0     0       0      0      0   
3      0     0       0         0      0         0     0       0      0      0   
4      0     0       0         0      0         0     0       0      0      0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795    0     0       0         0      1         0     0       0      0      0   
796    0     0       0         0      1         0     0       0      0      0   
797    0     0       0         0      0         0     0       0      1      0   
798    0     1       0         0      0         0     0       0      0      0   
799    0     0       0         0      0         0     0       0      0      0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0         0    0       0       1        0     0      0      0  
1         0    0       0       1        0     0      0      0  
2         0    0       0       1        0     0      0      0  
3         0    0       0       1        0     0      0      0  
4         0    0       0       0        0     0      0      0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795       0    0       0       0        0     0      0      0  
796       0    0       0       0        0     0      0      0  
797       0    0       0       0        0     0      0      0  
798       0    0       0       0        0     0      0      0  
799       0    0       0       0        0     0      0      1  

[800 rows x 18 columns]

In [33]:
z=x+y
z.head(5)

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0    0     0       0         0      0         0     0       0      0      1   
1    0     0       0         0      0         0     0       0      0      1   
2    0     0       0         0      0         0     0       0      0      1   
3    0     0       0         0      0         0     0       0      0      1   
4    0     0       0         0      0         0     1       0      0      0   

   Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0       0    0       0       1        0     0      0      0  
1       0    0       0       1        0     0      0      0  
2       0    0       0       1        0     0      0      0  
3       0    0       0       1        0     0      0      0  
4       0    0       0       0        0     0      0      0

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [49]:
corrt=z.join(df['Total'])
corrt.corr()['Total']

Bug        -0.145781
Dark        0.056154
Dragon      0.229705
Electric    0.020971
Fairy      -0.036698
Fighting    0.077786
Fire        0.078726
Flying      0.059383
Ghost       0.003641
Grass      -0.052592
Ground      0.015060
Ice         0.060248
Normal     -0.105331
Poison     -0.090441
Psychic     0.124688
Rock        0.032731
Steel       0.109703
Water      -0.021665
Total       1.000000
Name: Total, dtype: float64

In [40]:
column_1 = df["Total"]
column_2 = z["Bug"]
correlation = column_1.corr(column_2)
print(correlation)

-0.1457813612523841


# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [ ]:
# your code here