# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np

<module 'numpy' from 'C:\\Users\\oshav\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a=np.random.random((2,3,5))
a

array([[[0.7449222 , 0.51191312, 0.57246023, 0.39496855, 0.19852726],
        [0.99772422, 0.93077589, 0.88156305, 0.14112719, 0.0531537 ],
        [0.94959977, 0.28941493, 0.9870226 , 0.88282472, 0.67039439]],

       [[0.46652891, 0.32612485, 0.79746581, 0.90040019, 0.98232829],
        [0.0027728 , 0.30656821, 0.21795265, 0.48453103, 0.06300694],
        [0.76886002, 0.32306391, 0.08448855, 0.61850885, 0.84470531]]])

In [8]:
# Method 2
rg=np.random.default_rng(1)
a=rg.random((2,3,5))
a

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [ ]:
# Method 3


#### 4. Print *a*.


In [9]:
print(a)

[[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
  [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
  [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]]

 [[0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
  [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]
  [0.72478994 0.54122686 0.2768912  0.16065201 0.96992541]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
# your code here
b=np.ones((5,2,3))


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 6. Print *b*.


In [20]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [30]:
a.size

30

In [27]:
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
a+b #not because a and b are of different shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [38]:
# your code here
c=b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
# your code/answer here
d=a+c
d

array([[[1.51182162, 1.9504637 , 1.14415961, 1.94864945, 1.31183145],
        [1.42332645, 1.82770259, 1.40919914, 1.54959369, 1.02755911],
        [1.75351311, 1.53814331, 1.32973172, 1.7884287 , 1.30319483]],

       [[1.45349789, 1.1340417 , 1.40311299, 1.20345524, 1.26231334],
        [1.75036467, 1.28040876, 1.48519097, 1.9807372 , 1.96165719],
        [1.72478994, 1.54122686, 1.2768912 , 1.16065201, 1.96992541]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
# your code/answer here
a

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [42]:
d

array([[[1.51182162, 1.9504637 , 1.14415961, 1.94864945, 1.31183145],
        [1.42332645, 1.82770259, 1.40919914, 1.54959369, 1.02755911],
        [1.75351311, 1.53814331, 1.32973172, 1.7884287 , 1.30319483]],

       [[1.45349789, 1.1340417 , 1.40311299, 1.20345524, 1.26231334],
        [1.75036467, 1.28040876, 1.48519097, 1.9807372 , 1.96165719],
        [1.72478994, 1.54122686, 1.2768912 , 1.16065201, 1.96992541]]])

In [ ]:
#each element was added 

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [44]:
e=a*c
e

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

In [ ]:
# your code here

#### 13. Does *e* equal to *a*? Why or why not?


In [46]:
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [75]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

In [78]:
d_max


1.9807371998012386

In [52]:
d_min


1.0275591132430684

In [76]:
d_mean

1.5135194619749464

In [68]:
d

array([[[1.51182162, 1.9504637 , 1.14415961, 1.94864945, 1.31183145],
        [1.42332645, 1.82770259, 1.40919914, 1.54959369, 1.02755911],
        [1.75351311, 1.53814331, 1.32973172, 1.7884287 , 1.30319483]],

       [[1.45349789, 1.1340417 , 1.40311299, 1.20345524, 1.26231334],
        [1.75036467, 1.28040876, 1.48519097, 1.9807372 , 1.96165719],
        [1.72478994, 1.54122686, 1.2768912 , 1.16065201, 1.96992541]]])

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [59]:
f=np.empty((2,3,5), int)
f

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [98]:
for item in range(0,len(f)):
    print(item)
    for x in d:
        for y in x:
            for z in y:
                f[(z>d_min) &(z<d_mean)]=25
                f[(z>d_mean)& (z<d_max)]=75
                f[(z==d_mean)]=50
                f[(z==d_max)]=100
f

0
1


array([[[75, 75, 75, 75, 75],
        [75, 75, 75, 75, 75],
        [75, 75, 75, 75, 75]],

       [[75, 75, 75, 75, 75],
        [75, 75, 75, 75, 75],
        [75, 75, 75, 75, 75]]])

In [95]:
len(f)

2

In [115]:
for i1 in range (0,2):
    for i2 in range (0,3):
        for i3 in range (0,5):
            if d[i1,i2,i3]>d_min and d[i1,i2,i3]<d_mean:
                f[i1,i2,i3]=25
            elif d[i1,i2,i3]>d_mean and d[i1,i2,i3]<d_max:
                f[i1,i2,i3]=75
            elif d[i1,i2,i3]==d_mean:
                f[i1,i2,i3]=50
            elif d[i1,i2,i3]==d_max:
                f[i1,i2,i3]=100
            else:
                f[i1,i2,i3]=0
f

array([[[ 25,  75,  25,  75,  25],
        [ 25,  75,  25,  75,   0],
        [ 75,  75,  25,  75,  25]],

       [[ 25,  25,  25,  25,  25],
        [ 75,  25,  25, 100,  75],
        [ 75,  75,  25,  25,  75]]])

In [70]:
d

array([[[1.51182162, 1.9504637 , 1.14415961, 1.94864945, 1.31183145],
        [1.42332645, 1.82770259, 1.40919914, 1.54959369, 1.02755911],
        [1.75351311, 1.53814331, 1.32973172, 1.7884287 , 1.30319483]],

       [[1.45349789, 1.1340417 , 1.40311299, 1.20345524, 1.26231334],
        [1.75036467, 1.28040876, 1.48519097, 1.9807372 , 1.96165719],
        [1.72478994, 1.54122686, 1.2768912 , 1.16065201, 1.96992541]]])

In [106]:
d[0,1,1]

1.8277025938204416

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.